- name: Dotfiles config
  hosts: local

  vars_files:
     - ./vars/secrets.yaml
  roles:
    - role: zsh
      tags:
        - zsh
    - role: nvim
      tags:
        - nvim
    - role: core
      tags:
        - core
    - role: asdf
      tags:
        - languages
    - role: ssh
      tags:
        - ssh
