- name: Dotfiles config
  hosts: local

  vars_files:
     - ./vars/secrets.yaml
  roles:
    - role: zsh
      tags:
        - tools
    - role: nvim
      tags:
        - tools
    - role: core
      tags:
        - tools
    - role: asdf
      tags:
        - tools
