- name: Install System Packages (coreutils, build-essential, cmake, pkg-config, pthread)
  become: true
  ansible.builtin.package:
    name:
      - build-essential
      - cmake
      - pkg-config
      - libpthread-stubs0-dev
      - coreutils

- name: Install System Packages (lua, unzip, libtool, libtool-bin, gettext, git)
  become: true
  ansible.builtin.package:
    name:
      - lua5.1
      - unzip
      - libtool
      - libtool-bin
      - gettext
      - git

- name: Install Clang
  become: true
  ansible.builtin.package:
    name:
      - clang
