- name: Clone asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf

- name: Install GO
  ansible.builtin.shell:
    cmd: asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
